### ISSUE TITLE
Nested menus with portals

### ISSUE THREAD

**Issue by HakanKOCAK** [ycs77/headlessui-float#56] opened 2023-04-29 10:14 UTC
**Use Version**
 - @headlessui/react": "^1.7.14",
 - "@headlessui-float/react": "^0.11.1",
 - "react": "18.2.0",

**Question**
I have a headless ui popover component in which I render multiple headless ui comboboxes. When I pass portal true for comboboxes and popover altogether, when select any option from combobox, the parent popover perceives this as outside click and closes itself. Any solution for this?

**Screenshots**
<img width="375" alt="Screenshot 2023-04-29 at 13 11 47" src="https://user-images.githubusercontent.com/34274757/235297494-cffbc847-6001-4712-8c0e-6a70572952c0.png">

<img width="432" alt="Screenshot 2023-04-29 at 13 12 05" src="https://user-images.githubusercontent.com/34274757/235297461-fbd1bbe5-90df-4629-9dbe-91f7bc8b122d.png">
3d3ffb0-0640-41fc-8dc4-18219f03b200.png">

<img width="1016" alt="Screenshot 2023-04-29 at 13 13 27" src="https://user-images.githubusercontent.com/34274757/235297464-615a72ff-d18f-41a0-8d58-40505aac0c46.png">

**Comment by ycs77** [comment] 2023-05-05 08:32
Hi @HakanKOCAK, please provide a minimal reproducible example (like github repo, codesandbox, stackblitz...), it is recommended to fork the Headless UI Flaot's [React Demo](https://headlessui-float.vercel.app/react/quick-start.html#online-demo) to reproduce.

**Comment by ycs77** [comment] 2023-08-21 13:53
I will close this issue because there is no minimal reproducible example for this bug provided, if you have other issues can to open a new issue.

**Closed by ycs77** 2023-08-21 13:53 UTC
Labels: question
