### ISSUE TITLE
Should be wrapped in act(...)

### ISSUE THREAD

**Issue by razzeee** [ycs77/headlessui-float#60] opened 2023-05-19 07:40 UTC
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.14
 - Headless UI Float: v0.11.2
 - Framework: react v18.2
 - `@floating-ui/core`: v1.2.6
 - `@floating-ui/dom`: v1.2.7

**Describe the bug**
Running tests with the file under test using this component causes:

```
  console.error
    Warning: An update to Float inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at /home/klampe/dev/slashskills/node_modules/@headlessui-float/react/dist/headlessui-float.cjs:27:11232
        at div
        at OpenClosedProvider (/home/klampe/dev/slashskills/node_modules/@headlessui/react/dist/headlessui.dev.cjs:1011:31)
        at PopoverFn (/home/klampe/dev/slashskills/node_modules/@headlessui/react/dist/headlessui.dev.cjs:4828:54)
```

There is also an issue over at https://github.com/testing-library/testing-library-docs/issues/1255

It seemed to only show up after the react 18 update, but I'm unsure. Maybe it's even expected, that we need to do that, as the docs don't have any test examples :)

**Comment by ycs77** [comment] 2023-08-21 14:06
Hi @razzeee, please provide a minimal reproducible example (like github repo, codesandbox, stackblitz...), it is recommended to fork the Headless UI Flaot's [Online Demo](https://headlessui-float.vercel.app/react/quick-start.html#online-demo) to reproduce.

**Comment by razzeee** [comment] 2023-08-23 15:08
FYI, we currently have to add `act` (or waitFor in our case) around every component render, that headlessui-float is used in.

```ts
it('renders positive', async () => {
    render(<HoursPillRelative hours={-9} />)

    await waitFor(() => expect(screen.getByText('+9h')).toBeInTheDocument())
  })
 ```

That's our workaround for now. If it can be done in the library, it would spare quiet some work. I'll look into creating a repro asap.

**Comment by razzeee** [comment] 2023-08-26 14:16
I found it quiet hard to work it into the online demo, as there is no testing integrated at all. Creating a new redwoodjs app might just be easier for me.

**Comment by ycs77** [comment] 2023-08-26 14:43
Yes, I think may not need to use the online demo. I just need a minimal reproducible example.

I can only do my best to help you with the `act()` error, but I can't guarantee that I can solve it. The main reason is that I usually use Vue, not React, and I'm not very familiar with React.

However, I can give you a reference code: [Headless UI Float's unit test](https://github.com/ycs77/headlessui-float/tree/main/packages/react/test/unit). I also encountered this problem many times when writing unit tests, but I still couldn't understand why this error occurred. This test is driven by Vitest. I hope it can help you build a minimal example and solve this problem.

**Comment by ycs77** [comment] 2023-09-02 08:24
I found that this issue can only be solved by using `await waitFor()`, because I also wrote the unit test in the package in the same way:

https://github.com/ycs77/headlessui-float/blob/d2d19f1e7a18d81e2cd59b20511a1b8dcf3d5c42/packages/react/test/unit/components.test.tsx#L6-L38

However, I created a util function based on the usage of Floating UI, which can help your code look more concise:

https://github.com/ycs77/headlessui-float/blob/d2d19f1e7a18d81e2cd59b20511a1b8dcf3d5c42/packages/react/test/unit/utils/testing-library.ts#L18

https://github.com/ycs77/headlessui-float/blob/d2d19f1e7a18d81e2cd59b20511a1b8dcf3d5c42/packages/react/test/unit/utils/testing-library.ts#L25

I hope this can help you.

However, I think this issue cannot be solved in the package, so I will close this issue for now. If you have a better solution, please send a PR.

**Closed by ycs77** 2023-09-02 08:24 UTC
Labels: bug
